/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LakesRouteImport } from './routes/lakes'
import { Route as DataRouteImport } from './routes/data'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ChwRouteImport } from './routes/chw'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LakesLakeIdRouteImport } from './routes/lakes.$lakeId'
import { Route as GlaciersGlacierIdRouteImport } from './routes/glaciers.$glacierId'
import { Route as ApiPublicLakesRouteImport } from './routes/api/public/lakes'
import { Route as ApiPublicKpisRouteImport } from './routes/api/public/kpis'
import { Route as ApiPublicAlertsRouteImport } from './routes/api/public/alerts'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LakesRoute = LakesRouteImport.update({
  id: '/lakes',
  path: '/lakes',
  getParentRoute: () => rootRouteImport,
} as any)
const DataRoute = DataRouteImport.update({
  id: '/data',
  path: '/data',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ChwRoute = ChwRouteImport.update({
  id: '/chw',
  path: '/chw',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LakesLakeIdRoute = LakesLakeIdRouteImport.update({
  id: '/$lakeId',
  path: '/$lakeId',
  getParentRoute: () => LakesRoute,
} as any)
const GlaciersGlacierIdRoute = GlaciersGlacierIdRouteImport.update({
  id: '/glaciers/$glacierId',
  path: '/glaciers/$glacierId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicLakesRoute = ApiPublicLakesRouteImport.update({
  id: '/api/public/lakes',
  path: '/api/public/lakes',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicKpisRoute = ApiPublicKpisRouteImport.update({
  id: '/api/public/kpis',
  path: '/api/public/kpis',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAlertsRoute = ApiPublicAlertsRouteImport.update({
  id: '/api/public/alerts',
  path: '/api/public/alerts',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/alerts': typeof AlertsRoute
  '/chw': typeof ChwRoute
  '/dashboard': typeof DashboardRoute
  '/data': typeof DataRoute
  '/lakes': typeof LakesRouteWithChildren
  '/login': typeof LoginRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/glaciers/$glacierId': typeof GlaciersGlacierIdRoute
  '/lakes/$lakeId': typeof LakesLakeIdRoute
  '/api/public/alerts': typeof ApiPublicAlertsRoute
  '/api/public/kpis': typeof ApiPublicKpisRoute
  '/api/public/lakes': typeof ApiPublicLakesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/alerts': typeof AlertsRoute
  '/chw': typeof ChwRoute
  '/dashboard': typeof DashboardRoute
  '/data': typeof DataRoute
  '/lakes': typeof LakesRouteWithChildren
  '/login': typeof LoginRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/glaciers/$glacierId': typeof GlaciersGlacierIdRoute
  '/lakes/$lakeId': typeof LakesLakeIdRoute
  '/api/public/alerts': typeof ApiPublicAlertsRoute
  '/api/public/kpis': typeof ApiPublicKpisRoute
  '/api/public/lakes': typeof ApiPublicLakesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/alerts': typeof AlertsRoute
  '/chw': typeof ChwRoute
  '/dashboard': typeof DashboardRoute
  '/data': typeof DataRoute
  '/lakes': typeof LakesRouteWithChildren
  '/login': typeof LoginRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/glaciers/$glacierId': typeof GlaciersGlacierIdRoute
  '/lakes/$lakeId': typeof LakesLakeIdRoute
  '/api/public/alerts': typeof ApiPublicAlertsRoute
  '/api/public/kpis': typeof ApiPublicKpisRoute
  '/api/public/lakes': typeof ApiPublicLakesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/alerts'
    | '/chw'
    | '/dashboard'
    | '/data'
    | '/lakes'
    | '/login'
    | '/sitemap.xml'
    | '/glaciers/$glacierId'
    | '/lakes/$lakeId'
    | '/api/public/alerts'
    | '/api/public/kpis'
    | '/api/public/lakes'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/alerts'
    | '/chw'
    | '/dashboard'
    | '/data'
    | '/lakes'
    | '/login'
    | '/sitemap.xml'
    | '/glaciers/$glacierId'
    | '/lakes/$lakeId'
    | '/api/public/alerts'
    | '/api/public/kpis'
    | '/api/public/lakes'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/alerts'
    | '/chw'
    | '/dashboard'
    | '/data'
    | '/lakes'
    | '/login'
    | '/sitemap.xml'
    | '/glaciers/$glacierId'
    | '/lakes/$lakeId'
    | '/api/public/alerts'
    | '/api/public/kpis'
    | '/api/public/lakes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AlertsRoute: typeof AlertsRoute
  ChwRoute: typeof ChwRoute
  DashboardRoute: typeof DashboardRoute
  DataRoute: typeof DataRoute
  LakesRoute: typeof LakesRouteWithChildren
  LoginRoute: typeof LoginRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  GlaciersGlacierIdRoute: typeof GlaciersGlacierIdRoute
  ApiPublicAlertsRoute: typeof ApiPublicAlertsRoute
  ApiPublicKpisRoute: typeof ApiPublicKpisRoute
  ApiPublicLakesRoute: typeof ApiPublicLakesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lakes': {
      id: '/lakes'
      path: '/lakes'
      fullPath: '/lakes'
      preLoaderRoute: typeof LakesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data': {
      id: '/data'
      path: '/data'
      fullPath: '/data'
      preLoaderRoute: typeof DataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chw': {
      id: '/chw'
      path: '/chw'
      fullPath: '/chw'
      preLoaderRoute: typeof ChwRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lakes/$lakeId': {
      id: '/lakes/$lakeId'
      path: '/$lakeId'
      fullPath: '/lakes/$lakeId'
      preLoaderRoute: typeof LakesLakeIdRouteImport
      parentRoute: typeof LakesRoute
    }
    '/glaciers/$glacierId': {
      id: '/glaciers/$glacierId'
      path: '/glaciers/$glacierId'
      fullPath: '/glaciers/$glacierId'
      preLoaderRoute: typeof GlaciersGlacierIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/lakes': {
      id: '/api/public/lakes'
      path: '/api/public/lakes'
      fullPath: '/api/public/lakes'
      preLoaderRoute: typeof ApiPublicLakesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/kpis': {
      id: '/api/public/kpis'
      path: '/api/public/kpis'
      fullPath: '/api/public/kpis'
      preLoaderRoute: typeof ApiPublicKpisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/alerts': {
      id: '/api/public/alerts'
      path: '/api/public/alerts'
      fullPath: '/api/public/alerts'
      preLoaderRoute: typeof ApiPublicAlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface LakesRouteChildren {
  LakesLakeIdRoute: typeof LakesLakeIdRoute
}

const LakesRouteChildren: LakesRouteChildren = {
  LakesLakeIdRoute: LakesLakeIdRoute,
}

const LakesRouteWithChildren = LakesRoute._addFileChildren(LakesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AlertsRoute: AlertsRoute,
  ChwRoute: ChwRoute,
  DashboardRoute: DashboardRoute,
  DataRoute: DataRoute,
  LakesRoute: LakesRouteWithChildren,
  LoginRoute: LoginRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  GlaciersGlacierIdRoute: GlaciersGlacierIdRoute,
  ApiPublicAlertsRoute: ApiPublicAlertsRoute,
  ApiPublicKpisRoute: ApiPublicKpisRoute,
  ApiPublicLakesRoute: ApiPublicLakesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
