/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as ChwRouteImport } from './routes/chw'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DataRouteImport } from './routes/data'
import { Route as LakesRouteImport } from './routes/lakes'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAlertsRouteImport } from './routes/admin.alerts'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as AdminCasesRouteImport } from './routes/admin.cases'
import { Route as AdminChwProfilesRouteImport } from './routes/admin.chw-profiles'
import { Route as AdminDistrictsRouteImport } from './routes/admin.districts'
import { Route as AdminFacilitiesRouteImport } from './routes/admin.facilities'
import { Route as AdminGlaciersRouteImport } from './routes/admin.glaciers'
import { Route as AdminLakesRouteImport } from './routes/admin.lakes'
import { Route as AdminProtocolsRouteImport } from './routes/admin.protocols'
import { Route as AdminSyncRouteImport } from './routes/admin.sync'
import { Route as AdminSystemHealthRouteImport } from './routes/admin.system-health'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as GlaciersGlacierIdRouteImport } from './routes/glaciers.$glacierId'
import { Route as LakesLakeIdRouteImport } from './routes/lakes.$lakeId'
import { Route as AdminGlaciersIndexRouteImport } from './routes/admin.glaciers.index'
import { Route as AdminGlaciersGlacierIdRouteImport } from './routes/admin.glaciers.$glacierId'
import { Route as AdminLakesIndexRouteImport } from './routes/admin.lakes.index'
import { Route as AdminLakesLakeIdRouteImport } from './routes/admin.lakes.$lakeId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const ChwRoute = ChwRouteImport.update({
  id: '/chw',
  path: '/chw',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DataRoute = DataRouteImport.update({
  id: '/data',
  path: '/data',
  getParentRoute: () => rootRouteImport,
} as any)
const LakesRoute = LakesRouteImport.update({
  id: '/lakes',
  path: '/lakes',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAlertsRoute = AdminAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCasesRoute = AdminCasesRouteImport.update({
  id: '/cases',
  path: '/cases',
  getParentRoute: () => AdminRoute,
} as any)
const AdminChwProfilesRoute = AdminChwProfilesRouteImport.update({
  id: '/chw-profiles',
  path: '/chw-profiles',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDistrictsRoute = AdminDistrictsRouteImport.update({
  id: '/districts',
  path: '/districts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFacilitiesRoute = AdminFacilitiesRouteImport.update({
  id: '/facilities',
  path: '/facilities',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGlaciersRoute = AdminGlaciersRouteImport.update({
  id: '/glaciers',
  path: '/glaciers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLakesRoute = AdminLakesRouteImport.update({
  id: '/lakes',
  path: '/lakes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProtocolsRoute = AdminProtocolsRouteImport.update({
  id: '/protocols',
  path: '/protocols',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSyncRoute = AdminSyncRouteImport.update({
  id: '/sync',
  path: '/sync',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSystemHealthRoute = AdminSystemHealthRouteImport.update({
  id: '/system-health',
  path: '/system-health',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const GlaciersGlacierIdRoute = GlaciersGlacierIdRouteImport.update({
  id: '/glaciers/$glacierId',
  path: '/glaciers/$glacierId',
  getParentRoute: () => rootRouteImport,
} as any)
const LakesLakeIdRoute = LakesLakeIdRouteImport.update({
  id: '/$lakeId',
  path: '/$lakeId',
  getParentRoute: () => LakesRoute,
} as any)
const AdminGlaciersIndexRoute = AdminGlaciersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminGlaciersRoute,
} as any)
const AdminGlaciersGlacierIdRoute = AdminGlaciersGlacierIdRouteImport.update({
  id: '/$glacierId',
  path: '/$glacierId',
  getParentRoute: () => AdminGlaciersRoute,
} as any)
const AdminLakesIndexRoute = AdminLakesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminLakesRoute,
} as any)
const AdminLakesLakeIdRoute = AdminLakesLakeIdRouteImport.update({
  id: '/$lakeId',
  path: '/$lakeId',
  getParentRoute: () => AdminLakesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/alerts': typeof AlertsRoute
  '/chw': typeof ChwRoute
  '/dashboard': typeof DashboardRoute
  '/data': typeof DataRoute
  '/lakes': typeof LakesRouteWithChildren
  '/login': typeof LoginRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/alerts': typeof AdminAlertsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/cases': typeof AdminCasesRoute
  '/admin/chw-profiles': typeof AdminChwProfilesRoute
  '/admin/districts': typeof AdminDistrictsRoute
  '/admin/facilities': typeof AdminFacilitiesRoute
  '/admin/glaciers': typeof AdminGlaciersRouteWithChildren
  '/admin/lakes': typeof AdminLakesRouteWithChildren
  '/admin/protocols': typeof AdminProtocolsRoute
  '/admin/sync': typeof AdminSyncRoute
  '/admin/system-health': typeof AdminSystemHealthRoute
  '/admin/users': typeof AdminUsersRoute
  '/glaciers/$glacierId': typeof GlaciersGlacierIdRoute
  '/lakes/$lakeId': typeof LakesLakeIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/glaciers/$glacierId': typeof AdminGlaciersGlacierIdRoute
  '/admin/lakes/$lakeId': typeof AdminLakesLakeIdRoute
  '/admin/glaciers/': typeof AdminGlaciersIndexRoute
  '/admin/lakes/': typeof AdminLakesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/alerts': typeof AlertsRoute
  '/chw': typeof ChwRoute
  '/dashboard': typeof DashboardRoute
  '/data': typeof DataRoute
  '/lakes': typeof LakesRouteWithChildren
  '/login': typeof LoginRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/alerts': typeof AdminAlertsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/cases': typeof AdminCasesRoute
  '/admin/chw-profiles': typeof AdminChwProfilesRoute
  '/admin/districts': typeof AdminDistrictsRoute
  '/admin/facilities': typeof AdminFacilitiesRoute
  '/admin/protocols': typeof AdminProtocolsRoute
  '/admin/sync': typeof AdminSyncRoute
  '/admin/system-health': typeof AdminSystemHealthRoute
  '/admin/users': typeof AdminUsersRoute
  '/glaciers/$glacierId': typeof GlaciersGlacierIdRoute
  '/lakes/$lakeId': typeof LakesLakeIdRoute
  '/admin': typeof AdminIndexRoute
  '/admin/glaciers/$glacierId': typeof AdminGlaciersGlacierIdRoute
  '/admin/lakes/$lakeId': typeof AdminLakesLakeIdRoute
  '/admin/glaciers': typeof AdminGlaciersIndexRoute
  '/admin/lakes': typeof AdminLakesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/alerts': typeof AlertsRoute
  '/chw': typeof ChwRoute
  '/dashboard': typeof DashboardRoute
  '/data': typeof DataRoute
  '/lakes': typeof LakesRouteWithChildren
  '/login': typeof LoginRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/alerts': typeof AdminAlertsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/cases': typeof AdminCasesRoute
  '/admin/chw-profiles': typeof AdminChwProfilesRoute
  '/admin/districts': typeof AdminDistrictsRoute
  '/admin/facilities': typeof AdminFacilitiesRoute
  '/admin/glaciers': typeof AdminGlaciersRouteWithChildren
  '/admin/lakes': typeof AdminLakesRouteWithChildren
  '/admin/protocols': typeof AdminProtocolsRoute
  '/admin/sync': typeof AdminSyncRoute
  '/admin/system-health': typeof AdminSystemHealthRoute
  '/admin/users': typeof AdminUsersRoute
  '/glaciers/$glacierId': typeof GlaciersGlacierIdRoute
  '/lakes/$lakeId': typeof LakesLakeIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/glaciers/$glacierId': typeof AdminGlaciersGlacierIdRoute
  '/admin/lakes/$lakeId': typeof AdminLakesLakeIdRoute
  '/admin/glaciers/': typeof AdminGlaciersIndexRoute
  '/admin/lakes/': typeof AdminLakesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/alerts'
    | '/chw'
    | '/dashboard'
    | '/data'
    | '/lakes'
    | '/login'
    | '/sitemap.xml'
    | '/admin/alerts'
    | '/admin/audit'
    | '/admin/cases'
    | '/admin/chw-profiles'
    | '/admin/districts'
    | '/admin/facilities'
    | '/admin/glaciers'
    | '/admin/lakes'
    | '/admin/protocols'
    | '/admin/sync'
    | '/admin/system-health'
    | '/admin/users'
    | '/glaciers/$glacierId'
    | '/lakes/$lakeId'
    | '/admin/'
    | '/admin/glaciers/$glacierId'
    | '/admin/lakes/$lakeId'
    | '/admin/glaciers/'
    | '/admin/lakes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/alerts'
    | '/chw'
    | '/dashboard'
    | '/data'
    | '/lakes'
    | '/login'
    | '/sitemap.xml'
    | '/admin/alerts'
    | '/admin/audit'
    | '/admin/cases'
    | '/admin/chw-profiles'
    | '/admin/districts'
    | '/admin/facilities'
    | '/admin/protocols'
    | '/admin/sync'
    | '/admin/system-health'
    | '/admin/users'
    | '/glaciers/$glacierId'
    | '/lakes/$lakeId'
    | '/admin'
    | '/admin/glaciers/$glacierId'
    | '/admin/lakes/$lakeId'
    | '/admin/glaciers'
    | '/admin/lakes'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/alerts'
    | '/chw'
    | '/dashboard'
    | '/data'
    | '/lakes'
    | '/login'
    | '/sitemap.xml'
    | '/admin/alerts'
    | '/admin/audit'
    | '/admin/cases'
    | '/admin/chw-profiles'
    | '/admin/districts'
    | '/admin/facilities'
    | '/admin/glaciers'
    | '/admin/lakes'
    | '/admin/protocols'
    | '/admin/sync'
    | '/admin/system-health'
    | '/admin/users'
    | '/glaciers/$glacierId'
    | '/lakes/$lakeId'
    | '/admin/'
    | '/admin/glaciers/$glacierId'
    | '/admin/lakes/$lakeId'
    | '/admin/glaciers/'
    | '/admin/lakes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  AlertsRoute: typeof AlertsRoute
  ChwRoute: typeof ChwRoute
  DashboardRoute: typeof DashboardRoute
  DataRoute: typeof DataRoute
  LakesRoute: typeof LakesRouteWithChildren
  LoginRoute: typeof LoginRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  GlaciersGlacierIdRoute: typeof GlaciersGlacierIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chw': {
      id: '/chw'
      path: '/chw'
      fullPath: '/chw'
      preLoaderRoute: typeof ChwRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data': {
      id: '/data'
      path: '/data'
      fullPath: '/data'
      preLoaderRoute: typeof DataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lakes': {
      id: '/lakes'
      path: '/lakes'
      fullPath: '/lakes'
      preLoaderRoute: typeof LakesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/alerts': {
      id: '/admin/alerts'
      path: '/alerts'
      fullPath: '/admin/alerts'
      preLoaderRoute: typeof AdminAlertsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cases': {
      id: '/admin/cases'
      path: '/cases'
      fullPath: '/admin/cases'
      preLoaderRoute: typeof AdminCasesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/chw-profiles': {
      id: '/admin/chw-profiles'
      path: '/chw-profiles'
      fullPath: '/admin/chw-profiles'
      preLoaderRoute: typeof AdminChwProfilesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/districts': {
      id: '/admin/districts'
      path: '/districts'
      fullPath: '/admin/districts'
      preLoaderRoute: typeof AdminDistrictsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/facilities': {
      id: '/admin/facilities'
      path: '/facilities'
      fullPath: '/admin/facilities'
      preLoaderRoute: typeof AdminFacilitiesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/glaciers': {
      id: '/admin/glaciers'
      path: '/glaciers'
      fullPath: '/admin/glaciers'
      preLoaderRoute: typeof AdminGlaciersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/lakes': {
      id: '/admin/lakes'
      path: '/lakes'
      fullPath: '/admin/lakes'
      preLoaderRoute: typeof AdminLakesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/protocols': {
      id: '/admin/protocols'
      path: '/protocols'
      fullPath: '/admin/protocols'
      preLoaderRoute: typeof AdminProtocolsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sync': {
      id: '/admin/sync'
      path: '/sync'
      fullPath: '/admin/sync'
      preLoaderRoute: typeof AdminSyncRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/system-health': {
      id: '/admin/system-health'
      path: '/system-health'
      fullPath: '/admin/system-health'
      preLoaderRoute: typeof AdminSystemHealthRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/glaciers/$glacierId': {
      id: '/glaciers/$glacierId'
      path: '/glaciers/$glacierId'
      fullPath: '/glaciers/$glacierId'
      preLoaderRoute: typeof GlaciersGlacierIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lakes/$lakeId': {
      id: '/lakes/$lakeId'
      path: '/$lakeId'
      fullPath: '/lakes/$lakeId'
      preLoaderRoute: typeof LakesLakeIdRouteImport
      parentRoute: typeof LakesRoute
    }
    '/admin/glaciers/': {
      id: '/admin/glaciers/'
      path: '/'
      fullPath: '/admin/glaciers/'
      preLoaderRoute: typeof AdminGlaciersIndexRouteImport
      parentRoute: typeof AdminGlaciersRoute
    }
    '/admin/glaciers/$glacierId': {
      id: '/admin/glaciers/$glacierId'
      path: '/$glacierId'
      fullPath: '/admin/glaciers/$glacierId'
      preLoaderRoute: typeof AdminGlaciersGlacierIdRouteImport
      parentRoute: typeof AdminGlaciersRoute
    }
    '/admin/lakes/': {
      id: '/admin/lakes/'
      path: '/'
      fullPath: '/admin/lakes/'
      preLoaderRoute: typeof AdminLakesIndexRouteImport
      parentRoute: typeof AdminLakesRoute
    }
    '/admin/lakes/$lakeId': {
      id: '/admin/lakes/$lakeId'
      path: '/$lakeId'
      fullPath: '/admin/lakes/$lakeId'
      preLoaderRoute: typeof AdminLakesLakeIdRouteImport
      parentRoute: typeof AdminLakesRoute
    }
  }
}

interface AdminGlaciersRouteChildren {
  AdminGlaciersGlacierIdRoute: typeof AdminGlaciersGlacierIdRoute
  AdminGlaciersIndexRoute: typeof AdminGlaciersIndexRoute
}

const AdminGlaciersRouteChildren: AdminGlaciersRouteChildren = {
  AdminGlaciersGlacierIdRoute: AdminGlaciersGlacierIdRoute,
  AdminGlaciersIndexRoute: AdminGlaciersIndexRoute,
}

const AdminGlaciersRouteWithChildren = AdminGlaciersRoute._addFileChildren(
  AdminGlaciersRouteChildren,
)

interface AdminLakesRouteChildren {
  AdminLakesLakeIdRoute: typeof AdminLakesLakeIdRoute
  AdminLakesIndexRoute: typeof AdminLakesIndexRoute
}

const AdminLakesRouteChildren: AdminLakesRouteChildren = {
  AdminLakesLakeIdRoute: AdminLakesLakeIdRoute,
  AdminLakesIndexRoute: AdminLakesIndexRoute,
}

const AdminLakesRouteWithChildren = AdminLakesRoute._addFileChildren(
  AdminLakesRouteChildren,
)

interface AdminRouteChildren {
  AdminAlertsRoute: typeof AdminAlertsRoute
  AdminAuditRoute: typeof AdminAuditRoute
  AdminCasesRoute: typeof AdminCasesRoute
  AdminChwProfilesRoute: typeof AdminChwProfilesRoute
  AdminDistrictsRoute: typeof AdminDistrictsRoute
  AdminFacilitiesRoute: typeof AdminFacilitiesRoute
  AdminGlaciersRoute: typeof AdminGlaciersRouteWithChildren
  AdminLakesRoute: typeof AdminLakesRouteWithChildren
  AdminProtocolsRoute: typeof AdminProtocolsRoute
  AdminSyncRoute: typeof AdminSyncRoute
  AdminSystemHealthRoute: typeof AdminSystemHealthRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAlertsRoute: AdminAlertsRoute,
  AdminAuditRoute: AdminAuditRoute,
  AdminCasesRoute: AdminCasesRoute,
  AdminChwProfilesRoute: AdminChwProfilesRoute,
  AdminDistrictsRoute: AdminDistrictsRoute,
  AdminFacilitiesRoute: AdminFacilitiesRoute,
  AdminGlaciersRoute: AdminGlaciersRouteWithChildren,
  AdminLakesRoute: AdminLakesRouteWithChildren,
  AdminProtocolsRoute: AdminProtocolsRoute,
  AdminSyncRoute: AdminSyncRoute,
  AdminSystemHealthRoute: AdminSystemHealthRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface LakesRouteChildren {
  LakesLakeIdRoute: typeof LakesLakeIdRoute
}

const LakesRouteChildren: LakesRouteChildren = {
  LakesLakeIdRoute: LakesLakeIdRoute,
}

const LakesRouteWithChildren = LakesRoute._addFileChildren(LakesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  AlertsRoute: AlertsRoute,
  ChwRoute: ChwRoute,
  DashboardRoute: DashboardRoute,
  DataRoute: DataRoute,
  LakesRoute: LakesRouteWithChildren,
  LoginRoute: LoginRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  GlaciersGlacierIdRoute: GlaciersGlacierIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
